---
# handlers file for logstash
- name: start logstash
  service:
    name: logstash
    state: started
- name: start logstash
  service:
    name: logstash
    state: stoped
- name: start logstash
  service:
    name: logstash
    state: restarted
