---
# tasks file for kibana
- name: Installing Kibana
  apt:
    name: kibana
    update_cache: yes
    state: present

- name: Coping Kibana config file
  template:
    src: kibana.j2
    dest: "/etc/kibana/kibana.yml"
  notify:
    - restart kibana
