---
# tasks file for docker
- name: Installing Docker dependencies!
  apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Adding Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Installing Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
...
